### PR TITLE
fix(cookie): fix cookie being cleared for get

### LINKED ISSUE #895: driver.get调用两次，分别都需要登录，第一次登录成功，第二次又跳转至登录
* **Macaca Version**:"macaca-wd": "^2.1.1","macaca-electron": "2",

* **初始化**:
driver.initWindow({
      platformName: platform,
      browserName: browser,
      userAgent: 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0 AliApp(LA/1.0.0) iPhone Macaca Custom UserAgent Language/en_USMozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0 AliApp(LA/1.0.0) iPhone Macaca Custom UserAgent Language/en_US',
      width: 414,
      height: 736,
      deviceScaleFactor: 2,
      chromeOptions: {
        args: [],
        extensions: [],
        mobileEmulation: {
          deviceName: 'iPhone 6'
        }
      }
    })

* **用例**:
driver.get(`${url}`)
      .elementByCss(
        '#welcome-page > div.login-blocks.show-login-register-link > a.show-pwd-login-link'
      )
      .click()
      .elementById('fm-login-id')
      .sendKeys(username)
      .elementById('fm-login-password')
      .sendKeys(password)
      .elementByCss('#login-form > div.fm-btn > button')
      .click()
      .get(`${url_temp}`) 
  })
* **问题说明**:两个get的页面都需要登录，第一个登录成功了，为什么第二个get的时候  页面又要登录了

### PR DESCRIPTION
**Pull request by paradite**
fix https://github.com/alibaba/macaca/issues/895

### CODE REVIEW

File: lib/runner.js [hunk 1]
```diff
@@ -82,24 +82,30 @@ const wrapElectronResult = (value, status, message) => {
...
-      }
+      logger.debug('window has been loaded.');
+      process.send(wrapElectronResult());
     });
+    if (process.env.MACACA_ELECTRON_DEVTOOLS) {
+      mainWindow.openDevTools();
+    }
+    // this seems to remove cookies as well, disabling it first
+    // TODO: check if it is fixed in latest version of electron
+    // mainWindow.webContents.session.clearStorageData(
```
Comment (xudafeng) [inline lib/runner.js]: 这里不能去掉，很多产品依赖localstorage 比如 语雀
